#cloud-config
locale: en_US.UTF-8
#output: { all: '| tee -a /var/log/cloud-init-output.log' }
output: { all: "| tee -a /var/log/kafka-init-output.log" }

write_files:
  - content: |
      #!/usr/bin/env bash
      set -ex
      REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region`
      export AWS_DEFAULT_REGION=$${REGION}

      AZ=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .availabilityZone`
      export AWS_AZ=$${AZ}

      PRIVATE_IP=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .privateIp`

      kafka_config -a $${PRIVATE_IP} -E -S -i ${broker_id} -R $${AWS_AZ} -r ${repl_factor} -p ${num_partitions} -z ${zookeeper_connect}
    path: /root/init_kafka_config.sh
    permissions: '0777'
  - content: |
      #!/usr/bin/env bash
      #
      # Script to check the process and to post the status to CloudWatch.
      set -ex

      REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region`
      # get the process status
      value=`ps -ef | grep ${service} | grep -v grep | grep -v $0 | wc -l`

      # post the status
      aws --region $${REGION} cloudwatch put-metric-data --metric-name ${metric} \
          --namespace CMXAM/Kafka --value $value \
          --dimensions InstanceId=`curl http://169.254.169.254/latest/meta-data/instance-id` \
          --timestamp `date '+%FT%T.%N%Z'`

    path: /srv/${service}/${service}-status.sh
    permissions: '0700'
  - content: |
      while [ ! -f /root/.provisioning-finished ]
      do
          echo -n "#"
          sleep 1
      done
    path: /root/ensure-provisioned.sh
    permissions: '0777'

runcmd:
  - sh /root/init_kafka_config.sh
  - touch /root/.provisioning-finished && chmod 644 /root/.provisioning-finished
  - sh /root/ensure-provisioned.sh
  - echo '* * * * * /srv/${service}/${service}-status.sh' > /tmp/crontab
  - crontab -u ${service} /tmp/crontab
  - rm /tmp/crontab

